/**
 * Test harness: extracts the converter engine VERBATIM from docs/index.html
 * (no copy, no drift — the shipped bytes are what runs), materializes it as
 * an ES module, and exposes a convert() that mirrors the page's
 * convert-button handler.
 *
 * Note: this deliberately executes code extracted from our own repo file —
 * that is the system under test, equivalent to a test runner importing the
 * unit under test. Nothing untrusted flows in.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, '..', 'docs', 'index.html'), 'utf8');

const START = '/* ---------- detection ---------- */';
const END = '/* ---------- converter UI ---------- */';
const a = html.indexOf(START);
const b = html.indexOf(END);
if (a === -1 || b === -1 || b <= a) {
  throw new Error('Engine extraction markers not found in docs/index.html');
}
const engineSrc = html.slice(a, b);

// Materialize as a real module so Node parses/executes it natively
// (accurate stack traces, no string-eval).
const modulePath = join(__dirname, '.engine.extracted.mjs');
writeFileSync(
  modulePath,
  '// AUTO-GENERATED by harness.mjs — extracted from docs/index.html. Do not edit.\n' +
    engineSrc +
    '\nexport { tryJson, detect, splitDsv, flat, dataTables, LANG_RULES, EXT, splitFiles, codeTables, emitPack, __FPCODEC };\n'
);
export const engine = await import(pathToFileURL(modulePath).href);

/** Mirrors the page's convert-button handler (mode selection + naming). */
export async function convert(text) {
  const { detect, splitFiles, dataTables, codeTables, emitPack } = engine;
  const parts = splitFiles(text);
  const d = detect(parts ? parts[0].body : text);
  let tables, mode, schema;
  if (!parts && dataTables(d.kind, text)) {
    tables = dataTables(d.kind, text); mode = 'lossless'; schema = 'paste-v1';
  } else {
    const files = (parts || [{ name: null, body: text }]).map((f, i) => {
      const dk = detect(f.body) || { kind: 'text' };
      return {
        name: f.name || ('pasted' + (i ? '-' + (i + 1) : '') + '.' + (engine.EXT[dk.kind] || 'txt')),
        body: f.body,
        kind: dk.kind,
      };
    });
    tables = codeTables(files); mode = 'map'; schema = 'map-v1';
  }
  const sealed = emitPack(tables, schema); // emitPack now returns the complete sealed pack (codec encodeAuto)
  return { pack: sealed, mode, detected: d, tables };
}
